### ISSUE TITLE
Odds not display during Handover

### ISSUE THREAD

**Issue by coder77** [fifasports/UAT#30]
![image](https://user-images.githubusercontent.com/373000/116999371-1b104600-ad12-11eb-89c5-82ef26e6ddc6.png)

Betradar puller issue or PS/OS issue?

**Comment by samuel-zhen** [comment]
Currently the match is somehow ungrouped.
I assume it was mapped to betradar only at that time based on @coder77  description.

Betradar's match_id: **sr:match:23496281** (found by competitor name).
Handover happen at : 2021-05-04 11:47:32.442.

Issues found:
1. At handover time, p-betradar only send 102 FT. so OS cannot produce odds since missing 101 FT.
2. After some time, live odds dun have score. It will cause OS unable to pick up provider odds to generate.

![image](https://user-images.githubusercontent.com/25301914/117091754-dd053780-ad8e-11eb-9156-56943dbd346e.png)

**Comment by BrianRuchiadi** [comment]
Applied fix
